### ISSUE TITLE
no typescript support

### ISSUE THREAD

**Issue by ralpheichelberger** [heynext/v-contextmenu#115]
src/main.ts(12,25): error TS7016: Could not find a declaration file for module 'v-contextmenu'. '/app/node_modules/v-contextmenu/dist/index.common.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/v-contextmenu` if it exists or add a new declaration (.d.ts) file containing `declare module 'v-contextmenu';`
## 环境说明

- 组件版本：
- `Vue` 版本：
- 操作系统及版本：
- 浏览器及版本：

**Comment by kittors** [comment]
> ###
> ** [](/crystalfp)**

When I test according to the method you mentioned.prompt:No instance corresponding to contextmenu was found.
